#!/usr/bin/env bash
set -euo pipefail

: "${KIMI_API_KEY:?Set KIMI_API_KEY first.}"

PROJECT="${1:-.}"
KIMI_ANTHROPIC_BASE_URL="${KIMI_ANTHROPIC_BASE_URL:-PUT_CURRENT_ENDPOINT_HERE}"
KIMI_MODEL="${KIMI_MODEL:-PUT_CURRENT_MODEL_HERE}"

export ANTHROPIC_BASE_URL="$KIMI_ANTHROPIC_BASE_URL"
export ANTHROPIC_AUTH_TOKEN="$KIMI_API_KEY"

export ANTHROPIC_MODEL="$KIMI_MODEL"
export ANTHROPIC_DEFAULT_OPUS_MODEL="$KIMI_MODEL"
export ANTHROPIC_DEFAULT_SONNET_MODEL="$KIMI_MODEL"
export ANTHROPIC_DEFAULT_HAIKU_MODEL="$KIMI_MODEL"

cd "$PROJECT"
exec claude
